from sqlalchemy import Column, Integer, String, Float, Text, DateTime
from sqlalchemy.sql import func

from database import Base


# ============================================================
# SCAN MODEL
# ============================================================

class Scan(Base):
    __tablename__ = "scans"

    # Unique ID for every scan
    id = Column(Integer, primary_key=True, index=True)

    # Type of input:
    # URL, MESSAGE, or IMAGE
    input_type = Column(String(20), nullable=False)

    # Original URL or message submitted by the user
    input_data = Column(Text, nullable=False)

    # Neural network prediction
    ml_probability = Column(Float, nullable=True)

    # Final score generated by our hybrid risk engine
    risk_score = Column(Float, nullable=True)

    # LOW, MEDIUM, HIGH, or CRITICAL
    risk_level = Column(String(20), nullable=True)

    # Example:
    # Credential Phishing
    # Banking Scam
    # Delivery Scam
    # Job Scam
    threat_type = Column(String(100), nullable=True)

    # Threat intelligence result
    threat_intelligence = Column(String(100), nullable=True)

    # Explanation of why the input was considered suspicious
    indicators = Column(Text, nullable=True)

    # What the user should do
    recommendation = Column(Text, nullable=True)

    # Automatically store the scan time
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now()
    )